### ISSUE TITLE
NeuralNetwork_PERF and k

### ISSUE THREAD

**Issue by acheeseye** [acheeseye/ai-playing-checkers#7]
`NeuralNetwork_PERF` does not handle `k` or `-k` values when taking in an input (all testing is done with initial board state).

**Comment by woodchip-dev** [comment]
As the one who wrote it, do you think it would be better at this point to change `k` and `-k` to integer values (for example: `8` and `-8`) at the point where the values are initially outputted to a file? Or to add handling for  `k` and `-k` where the file is read in? Or perhaps add handling somewhere else before the values are used by `NeuralNetworkPERF`?

Personally, I think it may be best to not use `k` and `-k` at all and instead use integers. Doing it like that may mean more work initially to get all the necessary things changed, but it would likely mean less work later trying to get it to work because we wouldn't need to write handling to deal with `k` and `-k`.

Also, have you looked into ascii values? Using the decimal values of `k` and `K` could be another option.

**Comment by acheeseye** [comment]
Great idea! I think the value 2 should be sufficient for our purposes. I will get working on that soon (ish).

**Comment by acheeseye** [comment]
This is resolved and 2 & -2 values will be converted into appropriate king values (see `NeuralNetwork_PERF.cpp` lines 27~32 (may need testing).
